version: "3"
services:
  chrome:
    image: selenium/node-chrome:3.141.59-xenon
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST
      - HUB_PORT=4444
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
    - 28080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro